### ISSUE TITLE
Check whether libstruct handles badly formed SBML correctly

### ISSUE THREAD

**Issue by hsauro** [sys-bio/Libstructural#12]
What happens is a badly formed SBML file is loaded into libstructural?

I suspect it won't respond correctly.

**Comment by yosefmaru** [comment]
I found that loading a badly formed SBML file does not return any errors. If you try to run the methods on the loaded model, the output is either "There is no model to analyze" or just an empty list or array.

**Comment by hsauro** [comment]
I might have fixed this in the latest code.

Herbert

**Comment by fbergmann** [comment]
Since libsbml will just return a NULL model on invalid SBML this seemed like the right thing to do. I take it you now read the error messages from libsbml on a NULL model and do something with it?

**Comment by hsauro** [comment]
I modifed the code that that I get the libSBML message back.

Herbert
