### ISSUE TITLE
We need a 32-bit version as well

### ISSUE THREAD

**Issue by hsauro** [sys-bio/Libstructural#14]
Turns out I needed a 32 bit version of libstructural, so once the paper is submitted, update CMAKE so that is can also genreate 32 bit binaries.

**Comment by fbergmann** [comment]
That should already be possible, by simply specifying a 32bit generator ... i use the original libstruct (https://sourceforge.net/projects/libstruct/) with other generators, so unless you have added something calling: 

```
cmake -G "Visual Studio 15 2017 Win32" <other options>
```

should create you a 32bit visual studio project. To build from the command line just use a 32bit VS command prompt and use the "NMake Makefiles" generator.

**Comment by hsauro** [comment]
I created one but it took some fiddling to make it work.

Herbert
