### ISSUE TITLE
Is the 64 version of CMAKE copying files to BUILD_x32?

### ISSUE THREAD

**Issue by hsauro** [sys-bio/Libstructural#23]
Check to see if the 64 bit version is copying files to BUILD_x32 instead of BUILD_x64?

When I build the x64 verison, the files are being copies to BUILD_x32.

**Comment by yosefmaru** [comment]
I checked contents of both BUILD_x32 and BUILD_64 folder, and there is no crossover. You have to manually switch the folders if you are changing the bit configuration.

**Comment by hsauro** [comment]
When I build for 64 bit the files are being copied to build_x32.

How do I stop that?

H

**Comment by yosefmaru** [comment]
I have checked mine and nothing was being copied to build_x32 folder, when building for 64-bit binaries. To be sure, I emptied the build_x32 folder. 

Yosef
