### ISSUE TITLE
Once the paper is submitted, figure out a way to remove libstructuralPYTHON_wrap from INSTALL_x64 

### ISSUE THREAD

**Issue by hsauro** [sys-bio/Libstructural#6]
Currently the file libstructuralPYTHON_wrap.cxx is copied to INSTALL_x64, it probably shouldn't be there. Find another place to copy it to.

Deal with this issue after the paper has been submitted.

**Comment by yosefmaru** [comment]
I set the libstructuralPYTHON_wrap.cxx file to be copied in up-level SWIG folder.
